<?php


function myhook_menu() {
    $items['save-node-pdf'] = array(
      'title' => 'Save node to pdf',
      'page callback' => 'myhook_save_node_pdf_view',
      'access arguments' => array('administer nodes'),
    );
    return $items;
}


function myhook_save_node_pdf_view() {
  drupal_set_time_limit(0);
  module_load_include('inc', 'print', 'print.pages');
  module_load_include('inc', 'print_pdf_dompdf', 'print_pdf_dompdf.pages');
  $content_type = $_GET['content_type'];
  $node_id_from = $_GET['node_id_from'];
  $node_id_to   = $_GET['node_id_to'];

  if (!isset($content_type) || !isset($node_id_from) || !isset($node_id_to)) {
    return 'Please pass param after url example: http://example.com/save-node-pdf?content_type=article&node_id_from=10&node_id_to=20'; 
  }

  $lib_path = libraries_get_path('dompdf');
  //require_once($lib_path."/dompdf_config.inc.php");

  $sql = "SELECT nid FROM {node} WHERE type = :content_type  AND nid >= :node_id_from AND nid <= :node_id_to";
  $result = db_query($sql, array(
              ':content_type' => $content_type,
              'node_id_from' => $node_id_from,
              ':node_id_to' => $node_id_to
              )
            );

  $result = $result->fetchAll();
  $output = '';
  foreach ($result as $record) {
    save_pdf($record->nid);
    $output .= 'Save node-'.$record->nid.'.pdf';
    $output .= "<br />";
    $output .= "<br />";
  }
  $output .= 'All pdf file in <b>sites/default/files/pdf_output/</b> folder';
  return $output;

}

function save_pdf($nid) {
  $node = print_controller($nid, 'html');
  $html = theme('print', array('node' => $node, 'format' => 'pdf'));
  $html = preg_replace('!<tbody[^>]*?>|</tbody>!i', '', $html);
  $pattern = '!<(img\s[^>]*?)>!is';
  $html = preg_replace_callback($pattern, '_print_rewrite_urls', $html);


  // Convert the a href elements, to make sure no relative links remain
  $pattern = '!<(a\s[^>]*?)>!is';
  $html = preg_replace_callback($pattern, '_print_rewrite_urls', $html);
  // And make anchor links relative again, to permit in-PDF navigation

  //$html = file_get_contents($GLOBALS['base_url'].'/printpdf/'.$nid);; 

  /*
  return false;
  //$html = file_get_contents($GLOBALS['base_url'].'/print/'.$nid);; 
  $dompdf = new DOMPDF;
  $dompdf->set_base_path('/drupal7-4/');
  $dompdf->set_host('localhost');
  $dompdf->set_protocol('http://');
  $dompdf->load_html($html);
  $dompdf->render();
  $pdfoutput = $dompdf->output();
  */
  $meta = array(
    'url' => 'http://localhost/drupal7-4/',
  );
  $pdfoutput = print_pdf_dompdf_print_pdf_generate($html, $meta);
  //  Checks whether there is an output folder inside sites/default/files
  if (!is_dir('public://pdf_output')) {
    mkdir("public://pdf_output", 0777);
  //  Creates a folder and changes its permissions

  }
  $filename = 'sites/default/files/pdf_output/' . 'node-'.$nid.'.pdf';
  $fp = fopen($filename, "w+");
  fwrite($fp, $pdfoutput);
  //  Writes the pdf output to a file
  fclose($fp);

}
